export const END_POINTS = {
    apiProyectoList: 'http://localhost:8009/listar',
    apiProyectoAdd: 'http://localhost:8009/crear',
    apiProyectoEdit: 'http://localhost:8009/editar',
    apiProyectoDelete: 'http://localhost:8009/eliminar',
    apiProgramaList: 'http://localhost:8009/programa/listar',
    apiProgramaTallerAdd: 'http://localhost:8009/taller/crear',
    apiProgramaTallerEdit: 'http://localhost:8009/taller/editar',
    apiTallerDelete: 'http://localhost:8009/taller/eliminar',
    apiTallerList: 'http://localhost:8009/taller/listar',
    apiTallerById: 'http://localhost:8009/taller/ver',
    apiFacultadList: 'http://localhost:8333/facultad/listar',
    apiCarreraList: 'http://localhost:8333/carrera/listar',
    apiCicloList: 'http://localhost:8333/ciclo/listar',
    apiCursoList: 'http://localhost:8333/curso/listar',
    apiEstudianteList: 'http://localhost:8041/listar',
    apiPersonaList: 'http://localhost:8083/persona/listar',
    apiAsistenciaList: 'http://localhost:8901/listar',
    apiAsistenciaPersonaList: 'http://localhost:8901/listar-asistencia-persona',
    apiAsistenciaPersonaAdd: 'http://localhost:8901/crear-asistencia-persona',
    apiAsistenciaById: 'http://localhost:8901/ver',
    // apiAsistenciaUploadFile: 'http://localhost:8901/upload',
    apiAsistenciaAdd: 'http://localhost:8901/crear',
    apiDepartamentoList: 'http://localhost:8008/departamento/listar',
    apiProvinciaList: 'http://localhost:8008/provincia/listar',
    apiDistritoList: 'http://localhost:8008/distrito/listar',
    apiComunidadList: 'http://localhost:8008/comunidad/listar',
  };
  